name: Deploy to GitHub Pages (Auto-Host)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install & Build (if package.json)
        run: |
          if [ -f package.json ]; then
            npm ci
            if [ -f package.json ] && jq -r '.scripts.build // empty' package.json | grep -q . ; then
              npm run build
            fi
          fi
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
